### ISSUE TITLE
Dataset management

### ISSUE THREAD

**Issue by DeSchepperCedric** [sergiofenoll/project-databases#14]
* Create dataset
* Delete dataset
* View datasets

**Comment by MeyerJon** [comment]
Creating & deleting datasets is now possible via the DataLoader class (see [this branch](https://github.com/sergiofenoll/project-databases/tree/8-data-loader))

**Comment by MeyerJon** [comment]
The functionality for creating, deleting and viewing datasets has been implemented. There's also a very minimal user interface for this. 
I'm moving this issue to done for now.
