### ISSUE TITLE
Verslagen?

### ISSUE THREAD

**Issue by lfereman** [sergiofenoll/project-databases#41]
Waar vind ik de folder met de wekkelijkse meeting notes?

**Comment by sergiofenoll** [comment]
Deze zijn [hier op Google Drive](https://drive.google.com/drive/folders/1DXKPi517U_LaalKiTND5b05a3XTH7IG5?usp=sharing) te vinden.

**Comment by sergiofenoll** [comment]
Ter info, de link staat ook vermeld op de readme.

**Comment by lfereman** [comment]
Maak een kopie naar een mapje verslagen in github. 
Bedankt!

groetjes,
Len
