### ISSUE TITLE
Sorting for data tables

### ISSUE THREAD

**Issue by MeyerJon** [sergiofenoll/project-databases#44]
When sorting the table (by clicking the column head), it actually sorts on the previous column.
Also, search is nonfunctional

**Comment by MeyerJon** [comment]
Update: fixed search for 'access modal table', we should be able to re-use that code for any other tables that need to be searched using SQL.

**Comment by DeSchepperCedric** [comment]
@MeyerJon Can you fix the search option for the other tables as well please?

**Comment by MeyerJon** [comment]
Closing because this has been fixed, we only need to merge #67
