### ISSUE TITLE
Database model & ER-diagram

### ISSUE THREAD

**Issue by MeyerJon** [sergiofenoll/project-databases#7]
We need to create a solid design for our database that can be easily expanded upon. Ideally the amount of tables should be minimal and user-data shouldn't be restricted by, say, amount of columns. 
Once this design has been decided upon, we need to draw the corresponding ER-diagram and implement it.

**Comment by sergiofenoll** [comment]
The database model has been decided upon, we will utilize schemas to represent the different datasets of our application.
Please add ER-diagrams in the comments, once we have finalized (pretty) ER-diagrams they can be added to the repo.

If anyone knows of good software to design ER-diagrams, please do post it here.

**Comment by MeyerJon** [comment]
Reopened because we don't have our ER-diagram yet.
